### PR TITLE
Correct ddply

### PR DESCRIPTION
**Pull request by jsaintvanne**
Just correct a ddply function with no `plyr::` before whereas nearly all the others have it and work... ! 
Just don't know if it's good but it works for me after this!

### CODE REVIEW

**Comment by jsaintvanne** [comment]
don't really understand why it doesn't pass tests... :/

**Comment by Tomnl** [comment]
Thanks @jsaintvanne 

I am just restarting the travis build. It seems to be failing when trying to build the dependencies

**Comment by Tomnl** [comment]
Also, I am going to merge this into branch v1.11.4-dev rather than master and I will submit both changes to bioconductor as one version bump. If that is OK with you

**Comment by jsaintvanne** [comment]
Ho yes !! It reassures me :) Good luck for it and if I find something else I will send to you !

**Comment by jsaintvanne** [comment]
Yes yes no problem for me!! Do it where and when you want. I just prefer to tell to you about this things

**Comment by jsaintvanne** [comment]
Yes of course :) Let's go!!

**Pull request merged**
