### PR TITLE
xcms3 update

### PR DESCRIPTION
**Pull request by jsaintvanne**
Just few lines to be able to run XCMS 1.x or XCMS 3.x before msPurity !

The function added find the class of the xset object and transform it for a xcmsSet object (from XCMS 1.x)

### CODE REVIEW

**Comment by Tomnl** [comment]
Nice! Looks good, thanks Julien.

I will merge when the tests pass

**Comment by Tomnl** [comment]
I am going to merge this - some checks say they have not completed but travis looks like it has passed and I am happy with the changes.

**Comment by jsaintvanne** [comment]
Hi Thomas !

I find something that you can find when you process with XCMS 3.x...

The error is the following : 
```
> pa<-frag4feature(pa,xset)
Error in asMethod(object) : 
  Coercing an XCMSnExp with MS level > 1 is not yet supported!
```

I processed xset object like that : 
```
msmsPths <- list.files(system.file("extdata", "lcms", "mzML", package="msPurityData"), full.names = TRUE, pattern = "MSMS")
raw_data <- MSnbase::readMSData(msPths,mode = "onDisk")
xset <- xcms::findChromPeaks(raw_data, param = CentWaveParam())
xset <- xcms::groupChromPeaks(xset, param = PeakDensityParam(sampleGroups = numeric(nrow(xset@phenoData@data))))
xset <- adjustRtime(xset, param = PeakGroupsParam())
xset <- xcms::groupChromPeaks(xset, param = PeakDensityParam(sampleGroups = numeric(nrow(xdata@phenoData@data))))
```

I found a function named `filterMsLevel` which can select one level for MS datas but it erase the peakpicking... ! That can just save the adjustedRtime. 

So to have something which can be process normally, user MUST use something like 
```
if(length(unique(msLevel(raw_data)))!= 1){
	raw_data <- filterMsLevel(raw_data,msLevel=1)
}
```
It is include in our W4M Galaxy tools but I don't know if it is a good way for a package ?? 

Do you have some idea for that ?

**Comment by Tomnl** [comment]
Hi Julien,

Ok, so this is to do with

> as(xset, 'xcmsSet')
Error in asMethod(object) : 
  Coercing an XCMSnExp with MS level > 1 is not yet supported!

And yes for the time being adding the following will suffice (perhaps we could add to the example)

```
if(length(unique(msLevel(raw_data)))!= 1){
	raw_data <- filterMsLevel(raw_data,msLevel=1)
}
```

However, in the future it will be more useful to have the function fully compatible with the new version of XCMS.

**Comment by jsaintvanne** [comment]
Hi,

I asked for a function in XCMS in this issue https://github.com/sneumann/xcms/issues/362 but unfortunately they don't have yet something that can filter MS1 level after processing a peakpicking... 

The solution is effectively, for the moment, add something in the example like you said or also we can directly do something like
```
raw_data <- MSnbase::readMSData(msPths,mode = "onDisk", msLevel = 1)
```

An other question is : for you is it something wrong not to do peakpicking with MS2 level ?

**Comment by Tomnl** [comment]
>  for you is it something wrong not to do peakpicking with MS2 level ?

Sorry, I don't think I understand the question. Do you mean - "is XCMS peakpicking at MS2 level required?"

Not for msPurity but I imagine it could be useful for other processing.

In the future, I would like to update msPurity so is is more compatible with the new XCMS classes and the MSnBase backend.

**Comment by jsaintvanne** [comment]
> > for you is it something wrong not to do peakpicking with MS2 level ?
> 
> Sorry, I don't think I understand the question. Do you mean - "is XCMS peakpicking at MS2 level required?"
> 
> Not for msPurity but I imagine it could be useful for other processing.

Yes that what I mean :) sorry for my bad english ! 
My question is here because we spoke about retentionTime correction on MS2 datas during the process of peakpicking and if we select a msLevel to 1 we can't do that anymore...
> In the future, I would like to update msPurity so is is more compatible with the new XCMS classes and the MSnBase backend.

If users make the `filterMsLevel` before processing msPurity there is no problem with the new XCMS classes and MSnBase for the moment. 

You right : it should be better to update all the package with new classes but for the moment I think it can work like this with this little function :)

**Comment by Tomnl** [comment]
> My question is here because we spoke about retentionTime correction on MS2 datas during the process of peakpicking and if we select a msLevel to 1 we can't do that anymore...

For our processing - retention time correction is done only on the MS1 data and we just traceback for the MS2. So I don't think this is a problem.

**Pull request merged**
